apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::720545102396:role/eksctl-spot-cluster-2-nodegroup-s-NodeInstanceRole-S18IBACJQUWB
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::720545102396:user/EKS_Admin
      username: EKS_Admin

kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-10T05:15:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1149"
  uid: cbef897d-9aaf-4e57-a457-b5d90c1941df