apiVersion: v1 
kind: Pod
metadata: 
  name: labels-pod
  labels: 
    name: shiva
    course: DevOps
    trainer: Shiva rock 
  annotations:
    org.docker.kubernetes.maintainer: shiva
spec: 
  containers: 
    - name: nginx
      image: nginx
      ports: 
        containerPort: 80