apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    envFrom:
      - ConfigMapRef:
          name: course-config
    ports:
    - containerPort: 80