apiVersion: v1 
kind: Pod
metadata: 
  name: multi_container
spec: 
  container:
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80
    - name: almalinux
      image: almalinux